name: checkov
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

  workflow_dispatch:

jobs:
  scan:
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
      
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Install checkov
        run: pip install -U checkov

      - name: Run checkov
        env:
          PRISMA_API_URL: "${{ secrets.PRISMA_API_URL }}"
          BC_API_KEY: "${{ secrets.BC_API_KEY }}"
        run: |
          checkov --branch main --repo-id ${GITHUB_REPOSITORY} -d . --output cli --output sarif --output-file-path console,results.sarif --policy-metadata-filter policy.complianceStandard="ACSC Information Security Manual (ISM)",policy.complianceStandard="jneytchev-fedramp-low"
      
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        if: success() || failure()
        with:
          sarif_file: results.sarif
